/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.Controller;
import Logic.Participante;

/**
 *
 * @author Pared Baez Martin Jose<paredbaez.martin@gmail.com>
 */
public class InscribirParticipante extends javax.swing.JFrame {
    
    /**Instaciamos el Controlador Principal*/
           Controller controller = new Controller();

    /**
     * Creates new form IncribirParticipante
     */
    public InscribirParticipante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInscribirParticipante = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombreParticipante = new javax.swing.JLabel();
        lblApellidoParticipante = new javax.swing.JLabel();
        lblLocalidadParticipante = new javax.swing.JLabel();
        lblEdadParticipante = new javax.swing.JLabel();
        txtNombreParticipante = new javax.swing.JTextField();
        txtApellidoParticipante = new javax.swing.JTextField();
        txtLocalidadParticipante = new javax.swing.JTextField();
        txtEdadParticipante = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnInscribirParticipante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Inscripción de Participante");

        lblNombreParticipante.setText("Nombre: ");

        lblApellidoParticipante.setText("Apellido: ");

        lblLocalidadParticipante.setText("Localidad: ");

        lblEdadParticipante.setText("Edad: ");

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnInscribirParticipante.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnInscribirParticipante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/participante.png"))); // NOI18N
        btnInscribirParticipante.setText("Inscribir");
        btnInscribirParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirParticipanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInscribirParticipanteLayout = new javax.swing.GroupLayout(jpInscribirParticipante);
        jpInscribirParticipante.setLayout(jpInscribirParticipanteLayout);
        jpInscribirParticipanteLayout.setHorizontalGroup(
            jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInscribirParticipanteLayout.createSequentialGroup()
                .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInscribirParticipanteLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblTitulo))
                    .addGroup(jpInscribirParticipanteLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInscribirParticipanteLayout.createSequentialGroup()
                                .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpInscribirParticipanteLayout.createSequentialGroup()
                                            .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNombreParticipante)
                                                .addComponent(lblApellidoParticipante))
                                            .addGap(28, 28, 28))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInscribirParticipanteLayout.createSequentialGroup()
                                            .addComponent(lblLocalidadParticipante)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jpInscribirParticipanteLayout.createSequentialGroup()
                                        .addComponent(lblEdadParticipante)
                                        .addGap(45, 45, 45)))
                                .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLocalidadParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidoParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdadParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpInscribirParticipanteLayout.createSequentialGroup()
                                .addComponent(btnInscribirParticipante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(btnSalir)))))
                .addGap(23, 23, 23))
        );
        jpInscribirParticipanteLayout.setVerticalGroup(
            jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInscribirParticipanteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreParticipante)
                    .addComponent(txtNombreParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoParticipante)
                    .addComponent(txtApellidoParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidadParticipante)
                    .addComponent(txtLocalidadParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadParticipante)
                    .addComponent(txtEdadParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jpInscribirParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnInscribirParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInscribirParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInscribirParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Salimos de la Aplicacion
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInscribirParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirParticipanteActionPerformed
       /**Insctanciamos un Participante Vacio*/
        Participante participante = new Participante();
        /**Setamos los Atributos*/
        participante.setApellido(txtApellidoParticipante.getText());
        participante.setNombre(txtNombreParticipante.getText());
        participante.setLocalidad(txtLocalidadParticipante.getText());
        participante.setEdad(Integer.parseInt(txtEdadParticipante.getText()));
       /**Pasamos los datos a la Logica es decir 
        * al Controlador Principal.
        */
       controller.crearParticipante(participante);
    }//GEN-LAST:event_btnInscribirParticipanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribirParticipante;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jpInscribirParticipante;
    private javax.swing.JLabel lblApellidoParticipante;
    private javax.swing.JLabel lblEdadParticipante;
    private javax.swing.JLabel lblLocalidadParticipante;
    private javax.swing.JLabel lblNombreParticipante;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidoParticipante;
    private javax.swing.JTextField txtEdadParticipante;
    private javax.swing.JTextField txtLocalidadParticipante;
    private javax.swing.JTextField txtNombreParticipante;
    // End of variables declaration//GEN-END:variables
}
